[package]
name = "jinx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jayce = "12.0.0"
lazy_static = "1.4.0"
strum = "0.26.2"
strum_macros = "0.26.2"
